"use client";
// import type { Metadata } from "next";
import UserLocationContext from "@/context/UserLocationContext";
import { Titillium_Web } from "next/font/google";
import { useState } from "react";
import HeaderNavbar from "./components/HeaderNavbar";
import "./globals.css";
import NextAuthSessionProvider from "./provider/Provider";

const titillium = Titillium_Web({ subsets: ["latin"], weight: "400" });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [userLocation, setUserLocation] = useState([]);
  return (
    <html lang="en">
      <body className={titillium.className}>
        <NextAuthSessionProvider>
          <UserLocationContext.Provider
            value={{ userLocation, setUserLocation }}
          >
            <HeaderNavbar />
            {children}
          </UserLocationContext.Provider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
